(()=>{
const el=id=>document.getElementById(id),M=ROCModel;
let points=M.data('overlap'),threshold=1.01,timer=null,showAuc=false,eventText='Start: no instances are predicted positive. Lower the threshold to begin.';
const notes={overlap:'Some negative instances outrank positive ones. Scores 0.75 and 0.50 are tied across classes.',perfect:'Every positive instance ranks above every negative instance.',reversed:'Every negative instance ranks above every positive instance. The scores rank the classes in reverse.'};
function stop(){clearInterval(timer);timer=null;el('play').textContent='Play';}
function updateThreshold(t){const previous=M.counts(points,threshold);threshold=Math.round(t*100)/100;const current=M.counts(points,threshold),dp=current.tp-previous.tp,dn=current.fp-previous.fp;
eventText=dp||dn?`${dp>=0&&dn>=0?'Crossed':'Changed predictions:'} ${Math.abs(dp)} positive and ${Math.abs(dn)} negative instance${Math.abs(dp)+Math.abs(dn)===1?'':'s'}. ROC movement: ${dp>0?'up':dp<0?'down':'no vertical change'}; ${dn>0?'right':dn<0?'left':'no horizontal change'}.`:'No score crossed: the predictions and ROC point stay the same.';draw();}
function next(){const t=M.levels(points).find(v=>v<threshold-1e-9);if(t===undefined){stop();return;}updateThreshold(t);if(!M.levels(points).some(v=>v<threshold-1e-9))stop();}
function reset(){stop();threshold=1.01;eventText='Start: no instances are predicted positive. Lower the threshold to begin.';draw();}
function drawScores(){const svg=d3.select(el('scores')),w=el('scores').getBoundingClientRect().width,h=220,sx=d3.scaleLinear().domain([-.01,1.01]).range([58,w-22]);svg.attr('viewBox',`0 0 ${w} ${h}`).attr('height',h).attr('aria-label',`Scores for 10 positives and 10 negatives. Threshold ${threshold.toFixed(2)}. Scores at or above it are predicted positive.`);svg.selectAll('*').remove();
svg.append('rect').attr('x',sx(threshold)).attr('y',30).attr('width',Math.max(0,sx(1.01)-sx(threshold))).attr('height',136).attr('fill','var(--surface)');
[72,135].forEach((y,i)=>{svg.append('line').attr('x1',sx(0)).attr('x2',sx(1)).attr('y1',y).attr('y2',y).attr('stroke','var(--border)');svg.append('text').attr('x',12).attr('y',y+4).text(i?'−':'＋');});
svg.selectAll('path.dot').data(points).join('path').attr('class','dot').attr('d',p=>d3.symbol().type(p.positive?d3.symbolCircle:d3.symbolSquare).size(85)()).attr('transform',(p,i)=>`translate(${sx(p.score)},${(p.positive?72:135)+(i%3-1)*17})`).attr('fill',p=>p.score>=threshold?(p.positive?'var(--pos)':'var(--neg)'):'var(--bg)').attr('stroke',p=>p.positive?'var(--pos)':'var(--neg)').attr('stroke-width',2).append('title').text(p=>`${p.id}: true ${p.positive?'positive':'negative'}, score ${p.score.toFixed(2)}, predicted ${p.score>=threshold?'positive':'negative'}`);
svg.append('line').attr('x1',sx(threshold)).attr('x2',sx(threshold)).attr('y1',22).attr('y2',168).attr('stroke','var(--line)').attr('stroke-width',2);
svg.append('text').attr('x',Math.max(64,Math.min(w-62,sx(threshold)))).attr('y',16).attr('text-anchor','middle').text(`t = ${threshold.toFixed(2)}`);
svg.append('rect').attr('class','drag-line').attr('x',sx(threshold)-14).attr('y',20).attr('width',28).attr('height',150).attr('fill','transparent').call(d3.drag().on('start',stop).on('drag',ev=>updateThreshold(Math.max(-.01,Math.min(1.01,sx.invert(ev.x))))));
svg.append('g').attr('transform','translate(0,175)').call(d3.axisBottom(sx).tickValues(w<450?[0,.5,1]:[0,.2,.4,.6,.8,1]));svg.append('text').attr('x',w/2).attr('y',215).attr('text-anchor','middle').text('Model score');}
function drawRoc(){const svg=d3.select(el('roc')),w=el('roc').getBoundingClientRect().width,left=55,top=18,right=20,side=w-left-right,h=side+top+55,sx=d3.scaleLinear().domain([0,1]).range([left,left+side]),sy=d3.scaleLinear().domain([0,1]).range([top+side,top]);svg.attr('viewBox',`0 0 ${w} ${h}`).attr('height',h);svg.selectAll('*').remove();const all=M.curve(points),visible=all.filter(p=>p.threshold>=1||p.threshold>=threshold),current=M.counts(points,threshold);svg.attr('aria-label',`Current ROC point: false positive rate ${current.fpr.toFixed(2)}, true positive rate ${current.tpr.toFixed(2)}. ${visible.length-1} threshold groups crossed.`);
svg.append('rect').attr('x',left).attr('y',top).attr('width',side).attr('height',side).attr('fill','none').attr('stroke','var(--border)');
svg.append('path').attr('d',`M${sx(0)},${sy(0)}L${sx(1)},${sy(1)}`).attr('stroke','var(--muted)').attr('stroke-dasharray','5 5').attr('fill','none');
const path=d3.line().x(d=>sx(d.fpr)).y(d=>sy(d.tpr));
if(showAuc)svg.append('path').attr('d',path(all)).attr('fill','none').attr('stroke','var(--line)').attr('opacity',.25).attr('stroke-width',3);
svg.append('path').attr('d',path(visible)).attr('fill','none').attr('stroke','var(--line)').attr('stroke-width',3);
svg.selectAll('circle.step').data(visible).join('circle').attr('class','step').attr('cx',d=>sx(d.fpr)).attr('cy',d=>sy(d.tpr)).attr('r',2.5).attr('fill','var(--line)');
svg.append('circle').attr('cx',sx(current.fpr)).attr('cy',sy(current.tpr)).attr('r',6).attr('fill','var(--line)').attr('stroke','var(--bg)').attr('stroke-width',2);
svg.append('g').attr('transform',`translate(0,${top+side})`).call(d3.axisBottom(sx).ticks(5));svg.append('g').attr('transform',`translate(${left},0)`).call(d3.axisLeft(sy).ticks(5));svg.append('text').attr('x',left+side/2).attr('y',h-8).attr('text-anchor','middle').text('False positive rate (FPR)');svg.append('text').attr('transform',`translate(14,${top+side/2}) rotate(-90)`).attr('text-anchor','middle').text('True positive rate (TPR)');}
function draw(){const c=M.counts(points,threshold),a=M.auc(points);el('threshold').value=threshold;el('threshold-value').textContent=threshold.toFixed(2);el('example-note').textContent=notes[el('example').value];for(const key of ['tp','fp','tn','fn'])el(key).textContent=c[key];el('tpr-calculation').textContent=`${c.tp} / 10 = ${c.tpr.toFixed(2)}`;el('fpr-calculation').textContent=`${c.fp} / 10 = ${c.fpr.toFixed(2)}`;el('coordinate').textContent=`ROC point (FPR, TPR) = (${c.fpr.toFixed(2)}, ${c.tpr.toFixed(2)})`;el('event').textContent=eventText;const crossed=M.levels(points).filter(v=>v>=threshold).length;el('progress').textContent=`${crossed} / ${M.levels(points).length} distinct scores crossed`;el('next').disabled=el('play').disabled=crossed===M.levels(points).length;el('auc').hidden=!showAuc;el('auc-value').textContent=a.value.toFixed(3);el('auc-pairs').textContent=`${a.wins} correctly ordered pairs + ½ × ${a.ties} ties, out of ${a.total} pairs.`;drawScores();drawRoc();}
el('threshold').addEventListener('input',ev=>{stop();updateThreshold(Number(ev.target.value));});el('next').addEventListener('click',()=>{stop();next();});el('reset').addEventListener('click',reset);el('example').addEventListener('change',()=>{points=M.data(el('example').value);reset();});el('play').addEventListener('click',()=>{if(timer){stop();return;}el('play').textContent='Pause';timer=setInterval(next,850);next();});el('show-auc').addEventListener('click',()=>{showAuc=!showAuc;el('show-auc').textContent=showAuc?'Hide AUC':'Show AUC';el('show-auc').setAttribute('aria-expanded',String(showAuc));draw();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});new ResizeObserver(()=>{drawScores();drawRoc();}).observe(document.querySelector('main'));draw();
})();
